In [2]:
import pandas as pd

In [3]:
path = '../Sesion2/data_retail'

path_customers = f'{path}/customers'
path_orders = f'{path}/orders'
path_order_items = f'{path}/order_items'
path_products = f'{path}/products'
path_categories = f'{path}/categories'
path_departments = f'{path}/departments'

In [4]:
df_customers = pd.read_csv(path_customers, sep='|', header = None)
df_orders = pd.read_csv(path_orders,sep='|',header = None)
df_order_items = pd.read_csv(path_order_items,sep='|',header = None)
df_products = pd.read_csv(path_products,sep='|',header = None)
df_categories = pd.read_csv(path_categories,sep='|',header = None,names=['category_id','category_department_id','category_name'])
df_departments = pd.read_csv(path_departments,sep='|',header = None, names=['deparment_id','department_name'])

In [5]:
df_categories.head()

   category_id  category_department_id        category_name
0            1                       2             Football
1            2                       2               Soccer
2            3                       2  Baseball & Softball
3            4                       2           Basketball
4            5                       2             Lacrosse

In [6]:
df_departments

   deparment_id department_name
0             2         Fitness
1             3        Footwear
2             4         Apparel
3             5            Golf
4             6        Outdoors
5             7        Fan Shop

In [7]:
df_departments['department_name'].duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
Name: department_name, dtype: bool

In [8]:
df_departments['department_name'].duplicated().any()

np.False_

In [9]:
if df_departments['department_name'].duplicated().any():
    print("Hay departamentos duplicados en el dataframe")
    exit(1)
else:
    print("No existe duplicados")

No existe duplicados

In [10]:
def validate_department(df):
    if df_departments['department_name'].duplicated().any():
        print("Hay departamentos duplicados en el dataframe")
        exit(1)
    else:
        print("No existe duplicados")

In [11]:
validate_department(df_categories)

No existe duplicados

In [12]:
def validate_duplicated(df, column_name):
    if df[column_name].duplicated().any():
        print(f"Hay departamentos duplicados en el dataframe {column_name}")
        exit(1)
    else:
        print("No existe duplicados")

In [13]:
validate_duplicated(df_departments, 'department_name')

No existe duplicados

In [14]:
validate_duplicated(df_categories, 'category_department_id')

Hay departamentos duplicados en el dataframe category_department_id

In [15]:
valid_ids = set(df_departments['deparment_id'])
valid_ids

{2, 3, 4, 5, 6, 7}

In [16]:

def validate_ids(df, valid_ids):
    if not df_categories['category_department_id'].isin(valid_ids).all():
        print("Hay ids que no se encuentran en el dataframe")

    else:
        print("OK")

In [17]:
if not df_categories['category_department_id'].isin(valid_ids).all():
        print("Hay ids que no se encuentran en el dataframe")

Hay ids que no se encuentran en el dataframe

In [18]:
validate_ids(df_categories, valid_ids)

Hay ids que no se encuentran en el dataframe

In [19]:
#Realizando merge
df_departments

   deparment_id department_name
0             2         Fitness
1             3        Footwear
2             4         Apparel
3             5            Golf
4             6        Outdoors
5             7        Fan Shop

In [20]:
df_categories.head()

   category_id  category_department_id        category_name
0            1                       2             Football
1            2                       2               Soccer
2            3                       2  Baseball & Softball
3            4                       2           Basketball
4            5                       2             Lacrosse

In [21]:
#df_departments.merge(df_categories, df_departments.department_id = df_categories.category_department_id, )

In [22]:
df_departments.merge(df_categories, left_on='deparment_id', right_on='category_department_id', how='left')

,deparment_id,department_name,category_id,category_department_id,category_name
0,2,Fitness,1,2,Football
1,2,Fitness,2,2,Soccer
2,2,Fitness,3,2,Baseball & Softball
3,2,Fitness,4,2,Basketball
4,2,Fitness,5,2,Lacrosse
5,2,Fitness,6,2,Tennis & Racquet
6,2,Fitness,7,2,Hockey
7,2,Fitness,8,2,More Sports
8,3,Footwear,9,3,Cardio Equipment
9,3,Footwear,10,3,Strength Training
10,3,Footwear,11,3,Fitness Accessories
11,3,Footwear,12,3,Boxing & MMA
12,3,Footwear,13,3,Electronics
13,3,Footwear,14,3,Yoga & Pilates
14,3,Footwear,15,3,Training by Sport
15,3,Footwear,16,3,As Seen on TV!
16,4,Apparel,17,4,Cleats
17,4,Apparel,18,4,Men's Footwear
18,4,Apparel,19,4,Women's Footwear
19,4,Apparel,20,4,Kids' Footwear
20,4,Apparel,21,4,Featured Shops
21,4,Apparel,22,4,Accessories
22,5,Golf,23,5,Men's Apparel
23,5,Golf,24,5,Women's Apparel
24,5,Golf,25,5,Boys' Apparel
25,5,Golf,26,5,Girls' Apparel
26,5,Golf,27,5,Accessories
27,5,Golf,28,5,Top Brands
28,5,Golf,29,5,Shop By Sport
29,6,Outdoors,30,6,Men's Golf Clubs
30,6,Outdoors,31,6,Women's Golf Clubs
31,6,Outdoors,32,6,Golf Apparel
32,6,Outdoors,33,6,Golf Shoes
33,6,Outdoors,34,6,Golf Bags & Carts
34,6,Outdoors,35,6,Golf Gloves
35,6,Outdoors,36,6,Golf Balls
36,6,Outdoors,37,6,Electronics
37,6,Outdoors,38,6,Kids' Golf Clubs
38,6,Outdoors,39,6,Team Shop
39,6,Outdoors,40,6,Accessories
40,6,Outdoors,41,6,Trade-In
41,7,Fan Shop,42,7,Bike & Skate Shop
42,7,Fan Shop,43,7,Camping & Hiking
43,7,Fan Shop,44,7,Hunting & Shooting
44,7,Fan Shop,45,7,Fishing
45,7,Fan Shop,46,7,Indoor/Outdoor Games
46,7,Fan Shop,47,7,Boating
47,7,Fan Shop,48,7,Water Sports

In [23]:
df_departments.to_csv('deparments.csv', index=False)

In [24]:
df_departments.to_json('deparments.json', orient='records', indent=2)

In [25]:
import sqlalchemy as db
import pandas as pd

In [26]:
engine = db.create_engine('mysql+mysqlconnector://root:root@127.0.0.1:3310/retail_db?charset=utf8mb4')
conn = engine.connect()

In [28]:
df_departments.to_sql('deparments_2', con=conn, index=False)

6

In [32]:
pd.read_sql_table('deparments_2', con=conn)

   deparment_id department_name
0             2         Fitness
1             3        Footwear
2             4         Apparel
3             5            Golf
4             6        Outdoors
5             7        Fan Shop